/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ikusa
 */
public class Screen extends javax.swing.JDialog {

    /**
     * Creates new form Screen
     */
    public Screen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        incomeLabel = new javax.swing.JLabel();
        debtLabel = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        termLabel = new javax.swing.JLabel();
        paymentLabel = new javax.swing.JLabel();
        incomeField = new javax.swing.JTextField();
        debtField = new javax.swing.JTextField();
        rateField = new javax.swing.JTextField();
        termComboBox = new javax.swing.JComboBox();
        paymentField = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        housingPaymentLabel = new javax.swing.JLabel();
        otherObligationsLabel = new javax.swing.JLabel();
        maxPaymentLabel = new javax.swing.JLabel();
        mortgageLabel = new javax.swing.JLabel();
        housingPaymentSolution = new javax.swing.JLabel();
        otherObligationsSolution = new javax.swing.JLabel();
        maxPaymentSolution = new javax.swing.JLabel();
        mortgageSolution = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        years = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        incomeLabel.setText("Total Gross Income");

        debtLabel.setText("Total Monthly Debt");

        rateLabel.setText("Mortgage Interest Rate");

        termLabel.setText("Term");

        paymentLabel.setText("Down Payment");

        incomeField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                incomeFieldPropertyChange(evt);
            }
        });

        debtField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                debtFieldPropertyChange(evt);
            }
        });

        rateField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rateFieldPropertyChange(evt);
            }
        });

        termComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "15", "30" }));
        termComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                termComboBoxPropertyChange(evt);
            }
        });

        paymentField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        paymentField.setText("0");
        paymentField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                paymentFieldPropertyChange(evt);
            }
        });

        housingPaymentLabel.setText("Housing Payment");

        otherObligationsLabel.setText("Housing Payment + Other Obligations");

        maxPaymentLabel.setText("Maximum Payment Allowed");

        mortgageLabel.setText("Amount of Mortgage That Can Be Financed");

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        years.setText("years");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(maxPaymentLabel)
                                    .addGap(98, 98, 98)
                                    .addComponent(maxPaymentSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(otherObligationsLabel)
                                        .addComponent(housingPaymentLabel))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(housingPaymentSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(otherObligationsSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mortgageLabel)
                                    .addGap(20, 20, 20)
                                    .addComponent(mortgageSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rateLabel)
                            .addComponent(termLabel)
                            .addComponent(incomeLabel)
                            .addComponent(debtLabel)
                            .addComponent(paymentLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(paymentField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(termComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(years)))
                            .addComponent(rateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(debtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incomeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomeLabel)
                    .addComponent(incomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debtLabel)
                    .addComponent(debtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termLabel)
                    .addComponent(termComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(years))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentLabel)
                    .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(housingPaymentSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(housingPaymentLabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(otherObligationsLabel)
                    .addComponent(otherObligationsSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mortgageLabel)
                            .addComponent(mortgageSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxPaymentLabel))
                    .addComponent(maxPaymentSolution, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incomeFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_incomeFieldPropertyChange
      double income = Double.parseDouble(incomeField.getText());
      double debt = Double.parseDouble(debtField.getText());
      double rate = Double.parseDouble(rateField.getText());
      int term = Integer.parseInt(termComboBox.getSelectedItem().toString());
      double hp = Calc.housingPayment(income).toString();
      housingPaymentSolution.setText(hp);
      double hpp = Calc.housingPaymentPlus(income, debt).toString();
      otherObligationsSolution.setText(hpp);
      double mp = Calc.maxPay(income, debt);
      maxPaymentSolution.setText(mp);
    }//GEN-LAST:event_incomeFieldPropertyChange

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
      double income = Double.parseDouble(incomeField.getText());
      double debt = Double.parseDouble(debtField.getText());
      double rate = Double.parseDouble(rateField.getText());
      int term = Integer.parseInt(termComboBox.getSelectedItem().toString());
      double hp = Calc.housingPayment(income).toString();
      housingPaymentSolution.setText(hp);
      double hpp = Calc.housingPaymentPlus(income, debt).toString();
      otherObligationsSolution.setText(hpp);
      double mp = Calc.maxPay(income, debt);
      maxPaymentSolution.setText(mp);
    }//GEN-LAST:event_goButtonActionPerformed

    private void debtFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_debtFieldPropertyChange
      double income = Double.parseDouble(incomeField.getText());
      double debt = Double.parseDouble(debtField.getText());
      double rate = Double.parseDouble(rateField.getText());
      int term = Integer.parseInt(termComboBox.getSelectedItem().toString());
      double hp = Calc.housingPayment(income).toString();
      housingPaymentSolution.setText(hp);
      double hpp = Calc.housingPaymentPlus(income, debt).toString();
      otherObligationsSolution.setText(hpp);
      double mp = Calc.maxPay(income, debt);
      maxPaymentSolution.setText(mp);       
    }//GEN-LAST:event_debtFieldPropertyChange

    private void rateFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rateFieldPropertyChange
      double income = Double.parseDouble(incomeField.getText());
      double debt = Double.parseDouble(debtField.getText());
      double rate = Double.parseDouble(rateField.getText());
      int term = Integer.parseInt(termComboBox.getSelectedItem().toString());
      double hp = Calc.housingPayment(income).toString();
      housingPaymentSolution.setText(hp);
      double hpp = Calc.housingPaymentPlus(income, debt).toString();
      otherObligationsSolution.setText(hpp);
      double mp = Calc.maxPay(income, debt);
      maxPaymentSolution.setText(mp);
    }//GEN-LAST:event_rateFieldPropertyChange

    private void termComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_termComboBoxPropertyChange
      double income = Double.parseDouble(incomeField.getText());
      double debt = Double.parseDouble(debtField.getText());
      double rate = Double.parseDouble(rateField.getText());
      int term = Integer.parseInt(termComboBox.getSelectedItem().toString());
      double hp = Calc.housingPayment(income).toString();
      housingPaymentSolution.setText(hp);
      double hpp = Calc.housingPaymentPlus(income, debt).toString();
      otherObligationsSolution.setText(hpp);
      double mp = Calc.maxPay(income, debt);
      maxPaymentSolution.setText(mp);
    }//GEN-LAST:event_termComboBoxPropertyChange

    private void paymentFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_paymentFieldPropertyChange
      double income = Double.parseDouble(incomeField.getText());
      double debt = Double.parseDouble(debtField.getText());
      double rate = Double.parseDouble(rateField.getText());
      int term = Integer.parseInt(termComboBox.getSelectedItem().toString());
      double hp = Calc.housingPayment(income).toString();
      housingPaymentSolution.setText(hp);
      double hpp = Calc.housingPaymentPlus(income, debt).toString();
      otherObligationsSolution.setText(hpp);
      double mp = Calc.maxPay(income, debt);
      maxPaymentSolution.setText(mp);
    }//GEN-LAST:event_paymentFieldPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Screen dialog = new Screen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField debtField;
    private javax.swing.JLabel debtLabel;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel housingPaymentLabel;
    private javax.swing.JLabel housingPaymentSolution;
    private javax.swing.JTextField incomeField;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel maxPaymentLabel;
    private javax.swing.JLabel maxPaymentSolution;
    private javax.swing.JLabel mortgageLabel;
    private javax.swing.JLabel mortgageSolution;
    private javax.swing.JLabel otherObligationsLabel;
    private javax.swing.JLabel otherObligationsSolution;
    private javax.swing.JFormattedTextField paymentField;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JTextField rateField;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JComboBox termComboBox;
    private javax.swing.JLabel termLabel;
    private javax.swing.JLabel years;
    // End of variables declaration//GEN-END:variables
}
